---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "2048-deployment"
  namespace: 2048-game
spec:
  selector:
    matchLabels:
      app: "2048"
  replicas: 1
  template:
    metadata:
      labels:
        app: "2048"
    spec:
      containers:
        - image: agrawpri/2048-docker
          imagePullPolicy: Always
          name: "2048"
          ports:
            - containerPort: 9080
              protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 2048-ingress
  namespace: 2048-game
  labels:
    app: "2048"
spec:
  ingressClassName: nginx
  tls:
  rules:
  - host: "test1.${SECRET_DOMAIN}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "net-2048"
            port:
              number: 9080