apiVersion: v1
kind: Service
metadata:
  name: net-2048
  namespace: 2048-game
  labels:
    app: 2048
spec:
  type: NodePort
  ports:
    - port: 9080
      targetPort: 9080
  selector:
    app: "2048"