apiVersion: v1
kind: Service
metadata:
  name: net-2048
  namespace: 2048-game
  labels:
    app: 2048
spec:
  type: NodePort
  ports:
    - nodePort: 32000
      port: 80
      targetPort: 80
  selector:
    app: "2048"