---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-core-metallb
  namespace: flux-system
spec:
  path: ./cluster/apps/metallb-system/metallb/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-core-metallb-pools
  namespace: flux-system
spec:
  path: ./cluster/apps/metallb-system/metallb/pools
  dependsOn:
    - name: cluster-core-metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
