# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:EnEkLo/2BpI7F5vSX3WixZGT1LELeG8Y4dzyAQ2x5VyqBFLyU8Cp1A==,iv:xG4DWbsPkb/o0fQOhqZyGt8KlyTIQ0F/0NhfFg/aKuI=,tag:uKMxSd0bZEyJ5NaBqO2WRg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-10-07T10:14:41Z"
    mac: ENC[AES256_GCM,data:7ST+lyoCrtKMMwf8xqEoiIoXeQTrfcXFiu7xlu7sLmM3OP7CdYkPVygQ5O+pz7blV2CfrgAiNPIRfd73xzYpz7xqa+yDEV7nePbe0j2dnqM45Urp84Bm2SvxIxjRdld6uR/6+vrQxxl8mRtO+PyfTlXBqwoJ6+0OsMqGpTlxH94=,iv:Kz+zfzbnKzlQDdDCiMViqSku+aZMOuKBaR90F7/MLiY=,tag:OVWl+/jAmMEoh9brhi9fRQ==,type:str]
    pgp:
        - created_at: "2024-10-07T10:14:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+JgCgXimQvYAQ/+Kv9VT4+UYRieACw9IapPnVZXrRod1W2iEukmqtrUzqTY
            CnxG9dcQ31opehvUBeGA0lrwP//bRar0pRDhF9bDqStnlxWyJpiSUuRzj+XGSfyG
            eVLphQ25ze0u+Ga/3e+Yj9uSpAnUTVaarvPQKtDFsfjfTZh3OSjIaUUlBkkoRjN3
            6+Ec0hH2oXJDt7eCxG/ik5OqJFrOCxENyXjs1WUuCqFCMm/DLBAKrXHvwd3h9BAG
            /kDxjGk2W052oqzLvXx3oxSZF7ue19+WJMN4YZzTy+oCKZvUFZ2v9iW+UEeh8etA
            UfrV20ABmtKHPS2oVYZGmXI3+1s2OZlN7dTqttPuUm4C6ps26Vrvc2vSlqYRH7Y9
            L02XmK/avMY4EgGXcLCs/fTb4p0QzkD5fQhTph8jLI4Nl/+XVhk8WAxQ8b3qG/Km
            b9wBRf0gc7WqDC+cZnRbf5HIpTvMgX+5CjvKh+I9XmBsdhFz6Do7yTyT+gIEFr+N
            DQOwmt+b9EFWOyYUM8QBvmA9nDL+x7abelv6G9Gb9BkMkGdCtux45/TOZqG61LjH
            suTvI1C+Zu2GbVv6Z7btfYX2Qpyh9hHY9ucc4lU0/J+aNwP5jEhU/SfLJkGQSfwY
            qm0D6zxkBHNkli9HttBpMu5uvlZimD8nILYsgxyZMGxHtQZpJtyntvahEkPRRw7S
            XgG4TYkUlAvRaaCDYsxBeKI0csHYfZRfqMBm/sqOe4tJUzQM/zyLvA0TTRpAhGNj
            Y+t53dUXzqyeQU6ndV7XnCt6hj/4PKOjjwlVOa0yEBgOCLr5uMLoCKzM5qFWv4I=
            =SCq7
            -----END PGP MESSAGE-----
          fp: 42A5C4A02342A7270D8A4B153B6EC017AA0DACDF
        - created_at: "2024-10-07T10:14:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5UqdPN5/N2iAQ//eJLeljEYXf53iIoXDXIzfqVOFSymdAJFv+8Ch+SUP5+H
            VxqTP1nUDdfLmRb27qAlu8j4f8NkA3mBrqf9S8SW+37QhlmcjF9Hy1qbazw6OI/2
            jF6pSD0Ri9owKVh9pL4/J91lmh5TJw8dRxp/r1ZmG6gvOjMZGIwMtalFYU2cbSUl
            ifBrsupk1lPJlkxli4ndPiuMcfTT83sVOtQ5GCgHS+H6P97+VExU3IogprGNkiah
            BNwI49awInk/uHcEk4QDg6m63WEcRGOA4yS8prYC7JJ3ilm2x/PmDeR0o40XDswO
            0WVfTp3T/1WRuZ3MzCTpXhiV3nKOncXpbcqNgZRDSGdZ4GsqBThUAf5PW11uiWte
            rG4UsL6zmA86cR3yDtu8hmmX9HAzWP138gk8Ztw+h/e92cw8SpFzPERhxNvX+Brq
            WmdugfbnayoHN0iLFe5WDxbVqvIrPUyXYpyPlKW/ZOcwS6LiPm+2VLeDPlht3dN+
            y0MX77LHuAQ8RDitK1u+BtvZMaAKrq+ri5BtyQ2Log+95WIlGyxNy91EIEGsniRQ
            X2N5gfULKtY+0ndz/Bb4lfLTGRXn2o4ONAAuu/rp9iXIm0cCJ+B3bzFgd/eIJESB
            Zf+uS1B4aYZ3xuySZm7WrNI1K586nJOWpjZ6OHeH4msmv5n1Xb8sP9VF6+00qvfS
            XgGVSnwxV5R9ZDG5fd/ajXWBCY+RwVa6qSrSstTSiyRXSnNpgpkGUYpKJRWHDpTP
            Yk1LkeWxjrFY1XXF0M+AM0I04Kg4ksx/NgDatp5fiK6eTOTe4h8oDFcMj72ZeV4=
            =y+bP
            -----END PGP MESSAGE-----
          fp: 053EBE045469061BF2F43DB13652D7C79A5450D5
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
