# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:6iafe5jmptrIm9f7b7LTGZ8WD4QJoi9NuZiXTwip2Q/160lUR5+ctw==,iv:bszKZBK1VqRsj72F56vwgMbFRhIKsXTLOrUKBlKVb/E=,tag:PxhwghOuXQdJ63cnIvdelQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-10-06T22:28:30Z"
    mac: ENC[AES256_GCM,data:rItQLL5n3lmRtYIr0oNu4qxmegb2DyeVfiVBSdPxInqjWdHWu3b9ezk1/PEu9A3AN4xxrKdI2EuIg0DxfSLYxqcsRTtGw452pDF3AwTyas8RBkocZXcgIcaXlYFzh2GcKldA6u7qw/+rkqbwga6byQ3srDCB8vNiQEFLlLKPM40=,iv:suMoc/VbWi45qY6v+e3JErV5uPpNcvyBkHoa8CUC4Vg=,tag:9woVqiBTp4Myh2c3DXDEnQ==,type:str]
    pgp:
        - created_at: "2024-07-22T01:49:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7qnLr8BI6DaAQ/+J1IqGNUayt7m9/cgVrMAzlo0wP1c1Ae/P8rD8oGtsefL
            XjYTY4C0FdKPtc2lSYtoO5Dq8Rx+FQfmeRTdGuFczecEimuyOAyQDfQn8a9GTZ2w
            jnDe35FJ70rUJV2sLBzqqk5BRBkY6WU8nx0vX969RSfeCV7EBG47k8DnOuJu5CXv
            WmOFvKl6o69VbzSbEt9RLrF21ztzS/jwFyFEpheVzt3JSFwQcof/Ujer98eGl3o6
            DCD655lVy7QXMsoSEW5VV3OHHDSd002EpWXXikepWkjbzI0qyzct0bcMMgNh4o3B
            5xy9a/eKuV8H7jjm7HqfkRdLN0vjcZ9RXtxer0ZdHiR9ij9DndwgIHA7XepLlmqe
            LuIEVXYjqjHlMlqgP/4OPi67X+g7UOret0GUIFR+Rh+/hkUTDpFP1kmPzoU4Fx4r
            6fJ0n3l3C0I5Lym1xvd4AHlqjWZiOdMUXxzA1h6hHgjHJPcMOzgwJiCQ3l8DCy7x
            +1uoTAK1uD9KgcZyDuQ/bJNRgu5XlmQ1kA3mGuQMec+2buPADLwjVVSS6CpHZFNg
            2Jw4t14oGFqqJleiNyOAmcRok6MyotmmRwKW1B9cmDcUgdmgDLDAgaKWOcfjXb9Q
            fSBkSpx/4xKlf5O5xtNk+2AwAET3ZoKeYJR7QQgMqQl9Z8SmRqEfbSE5kg0B1rDS
            XAEvdKik/4UK69X+8Wr0H5Kurz3Ush0Qsud1boCoSeuhfTFwnSX0ZfpvPpUJYWAQ
            dEIi5jIBLZqyNPQ+F6XAKumpBbXiLUdGEcE3EXH8e500HEy9VWDtcgeSplSQ
            =YEyg
            -----END PGP MESSAGE-----
          fp: C9F3FB5066351BCB2639CEA99ADF52FE4D9761B6
        - created_at: "2024-07-22T01:49:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAzKuB24A4IZJARAAm2vSDzZNcGXzzOJ5nAL7Ekft1qOcoBo0zjyLFcWAWuIi
            pNVHH6QRe8NIbdmk7BnfQB99UvVZ/fQDgPVie/1HxMfjjEXwsGCWv0NRgTMPrafv
            n5OdclBVUPPZDGLBfC1C3Raon5qmM9Ef2fGR13U6/MibAf4lW22SeiKkSYvndMK+
            XrZSbv1dG3n8OqnGI/fL3cqyly89460h84pja7S5wKW8zB3m8qFOSu34qZZQBb06
            QyYqQIKVniXLGa+X8aaFToD+k1n4sda4synPa8eJb1th8V9zkGa9IT0eVK0j3O5K
            bFCA2otWkLJw9tLRqSNF6mrfmwyvRwLiuqGW5451/gm6FsuvFDwIZVmeYk2XhRSt
            u91bU1ULRiwwoUbdJERXR9OCOV1fPkX3fyG5oGAUXpoMXb/jm11fBUXe99SVT023
            nAC4O8hYGAqxIdON0tubSKyIXo9y2EV2XxdtwIChd6u/gzksvXCNH2JKcfGltx3K
            8IshQ1biOf6lRN/zEVZwL31+xiz7SRzUhdJvZatw7yM+ZIfBemCstC9vK4+j8Jgp
            8vOMCiVZyckY/n7+i2/bSxkTX28eentBpNsAUJT27XiqObmK8RB51GnMWPqr1ep3
            UPOM1cMTAxHRc8dNJRTOUiLhFGlt9II6MDQBuBl5+zJxcG2Leeel0xVsG5f8NE7S
            XAGOyjrCZbI5+jOU1lK67nuiVcDEl86ZLuI8zKxXdynmgHIzTtf0wLr3PQrV+2I/
            swrr1QnCoUZH3K6AI4CkKsjgb5GZU8sBa8oNnkXwG2iigOOp8Q7qPh+qssKY
            =ciu0
            -----END PGP MESSAGE-----
          fp: 669E2CBC2C4122406D54DC8A3D3C9E2C7992425D
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
